version: '3'

services:

  # reverse proxy
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy_plantsaver
    depends_on:
      - moisture-service
      - plantsaver-dashboard
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  # generate faux moisture service
  moisture-service:
    image: moisture-service
    container_name: moisture-service
    build:
        context: ./moisture-service
    ports:
      - 5001:5001
    restart: on-failure

  # weather-api
  # weather-service:
  #  image: weather-service
  #  container_name: weather-service
  #  build:
  #      context: ./weather-service
  #  ports:
  #    - 5002:5002
  #  restart: on-failure


  # dashboard
#  plantsaver-dashboard:
#    image: plantsaver-dashboard
#    container_name: plantsaver-dashboard
#  depends_on:
#      - moisture-service
      # - weather-service
#    ports:
#      - 8086:80
#    restart: on-failure
